/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelDtoSolution =
  typeof ChannelDtoSolution[keyof typeof ChannelDtoSolution];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelDtoSolution = {
  PLACEMENT: "PLACEMENT",
  REJECTION: "REJECTION",
} as const;
