/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelInfoDtoStatus =
  typeof ChannelInfoDtoStatus[keyof typeof ChannelInfoDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelInfoDtoStatus = {
  OK: "OK",
  ERROR: "ERROR",
} as const;
