/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChannelPageSettingsDirection } from "./channelPageSettingsDirection";
import type { ChannelPageSettingsTechStack } from "./channelPageSettingsTechStack";

export interface ChannelPageSettings {
  page?: number;
  size?: number;
  direction?: ChannelPageSettingsDirection;
  key?: string;
  link?: string;
  techStack?: ChannelPageSettingsTechStack;
  channelUser?: string;
  creatorFirstName?: string;
}
