/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelPageSettingsDirection =
  typeof ChannelPageSettingsDirection[keyof typeof ChannelPageSettingsDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelPageSettingsDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
