/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChannelResponse {
  id?: number;
  title?: string;
  username?: string;
  participantsCount?: number;
  avgPostReach?: number;
  avgPostReach12h?: number;
  avgPostReach48h?: number;
  errPercent?: number;
  dailyReach?: number;
  ciIndex?: number;
  mentionsCunt?: number;
  forwardsCount?: number;
  mentioningChannelsCount?: number;
}
