/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChannelCategoryDto {
  id?: string;
  name: string;
  description?: string;
}
