/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelDtoTechStack =
  typeof ChannelDtoTechStack[keyof typeof ChannelDtoTechStack];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelDtoTechStack = {
  Java: "Java",
  Python: "Python",
} as const;
