/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelStatDtoStatus =
  typeof ChannelStatDtoStatus[keyof typeof ChannelStatDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelStatDtoStatus = {
  OK: "OK",
  ERROR: "ERROR",
} as const;
