/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChannelInputDtoTechStack =
  typeof ChannelInputDtoTechStack[keyof typeof ChannelInputDtoTechStack];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelInputDtoTechStack = {
  Java: "Java",
  Python: "Python",
} as const;
