/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClientPageSettingsDirection =
  typeof ClientPageSettingsDirection[keyof typeof ClientPageSettingsDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientPageSettingsDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
