/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClientMessengerDtoType } from "./clientMessengerDtoType";

export interface ClientMessengerDto {
  type?: ClientMessengerDtoType;
  nickname?: string;
}
