/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClientMessengerDto } from "./clientMessengerDto";
import type { UserShortDto } from "./userShortDto";

export interface ClientDto {
  id?: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  phones?: string[];
  messengers?: ClientMessengerDto[];
  email: string;
  preferCommunicationMethods?: string;
  age?: number;
  sex?: string;
  noteAboutClient?: string;
  internalClickId?: string;
  creator?: UserShortDto;
  creationDate?: string;
}
