/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClientMessengerDtoType =
  typeof ClientMessengerDtoType[keyof typeof ClientMessengerDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientMessengerDtoType = {
  TELEGRAM: "TELEGRAM",
  VIBER: "VIBER",
  WHATSAPP: "WHATSAPP",
} as const;
