/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChannelPageSettings } from "./channelPageSettings";

export type GetChannelsParams = { pageSettings: ChannelPageSettings };
