/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetUserRoles200Item =
  typeof GetUserRoles200Item[keyof typeof GetUserRoles200Item];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserRoles200Item = {
  ADMIN: "ADMIN",
  OPERATOR: "OPERATOR",
  MANAGER: "MANAGER",
} as const;
