/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClientDto } from "./clientDto";

export interface IncomingRequestDto {
  id?: string;
  siteClientId: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  utmCampaignId?: number;
  utmContent?: string;
  utmContentId?: number;
  utmTerm?: string;
  utmTermId?: number;
  fbclid?: string;
  yclid?: string;
  yclidFirstVisitDate?: string;
  ymclid?: string;
  glickid?: string;
  glickidFirstVisitDate?: string;
  pageTitle?: string;
  dateTime?: string;
  userAgent?: string;
  eventSourceUrl?: string;
  fbc?: string;
  fbp?: string;
  rbClickid?: string;
  internalClickId?: string;
  client?: ClientDto;
  incomingRequestType?: string[];
  creationDate?: string;
}
