/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PageSettingsDirection =
  typeof PageSettingsDirection[keyof typeof PageSettingsDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageSettingsDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
