/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageSettingsDirection } from "./pageSettingsDirection";

export interface PageSettings {
  page?: number;
  size?: number;
  direction?: PageSettingsDirection;
  key?: string;
}
