/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradeStepFieldDto } from "./tradeStepFieldDto";

export interface TradeStepDto {
  id?: string;
  started?: boolean;
  name: string;
  stepFields?: TradeStepFieldDto[];
}
