/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TradeStepFieldDtoFieldType =
  typeof TradeStepFieldDtoFieldType[keyof typeof TradeStepFieldDtoFieldType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradeStepFieldDtoFieldType = {
  STRING: "STRING",
  CHECK_BOX: "CHECK_BOX",
  LIST: "LIST",
} as const;
