/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradeStepFieldDtoFieldType } from "./tradeStepFieldDtoFieldType";

export interface TradeStepFieldDto {
  id?: string;
  name: string;
  fieldType: TradeStepFieldDtoFieldType;
  required: boolean;
  values?: string[];
}
