/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradeDto } from "./tradeDto";

export type TradePageDtoGroupItems = { [key: string]: TradeDto[] };
