/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradePageDtoGroupItems } from "./tradePageDtoGroupItems";

export interface TradePageDto {
  totalPages?: number;
  totalElements?: number;
  groupItems?: TradePageDtoGroupItems;
}
