/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TradeStepShortDto } from "./tradeStepShortDto";
import type { ClientShortDto } from "./clientShortDto";
import type { TradeFieldDto } from "./tradeFieldDto";

export interface TradeDto {
  id?: string;
  identity?: string;
  site?: boolean;
  creationDate?: string;
  finishedDate?: string;
  step?: TradeStepShortDto;
  client?: ClientShortDto;
  fields?: TradeFieldDto[];
}
