/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserCreateDtoRolesItem } from "./userCreateDtoRolesItem";

export interface UserCreateDto {
  userName: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  birthDate?: string;
  locked: boolean;
  roles: UserCreateDtoRolesItem[];
  password: string;
}
