/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserCreateDtoRolesItem =
  typeof UserCreateDtoRolesItem[keyof typeof UserCreateDtoRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCreateDtoRolesItem = {
  ADMIN: "ADMIN",
  OPERATOR: "OPERATOR",
  MANAGER: "MANAGER",
} as const;
