/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserDtoRolesItem =
  typeof UserDtoRolesItem[keyof typeof UserDtoRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRolesItem = {
  ADMIN: "ADMIN",
  OPERATOR: "OPERATOR",
  MANAGER: "MANAGER",
} as const;
