/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserPageSettingsDirection =
  typeof UserPageSettingsDirection[keyof typeof UserPageSettingsDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPageSettingsDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
