/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDtoRolesItem } from "./userDtoRolesItem";
import type { UserShortDto } from "./userShortDto";

export interface UserDto {
  id?: string;
  userName: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  birthDate?: string;
  locked: boolean;
  roles: UserDtoRolesItem[];
  creationDate?: string;
  creator?: UserShortDto;
}
