/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserShortDto {
  id?: string;
  firstName?: string;
  lastName?: string;
  middleName?: string;
}
