/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserPageSettingsDirection } from "./userPageSettingsDirection";

export interface UserPageSettings {
  page?: number;
  size?: number;
  direction?: UserPageSettingsDirection;
  key?: string;
  userName?: string;
  firstName?: string;
}
